# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters

issues:
  exclude-files:
    - internal/provider/provider_test.go
  exclude-dirs:
    - vendor$
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused
    - govet

output:
  formats:
    - format: colored-line-number