repos:
  - repo: local
    hooks:
      - id: lint
        name: golangci-lint run
        language: system
        entry: bash -c 'golangci-lint run'
        files: '\.go$'
  - repo: local
    hooks:
      - id: gogenerate
        name: go generate
        language: system
        entry: bash -c 'go generate -v'
        files: '\.go$'
