repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        language: system
        entry: bash -c 'go fmt ./...'
        files: '\.go$'
  - repo: local
    hooks:
      - id: gogenerate
        name: go generate
        language: system
        entry: bash -c 'go generate -v'
        files: '\.go$'
