repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: Run golangci-lint
        language: system
        entry: golangci-lint run
        pass_filenames: false
        types: [go, gotmpl]
  - repo: local
    hooks:
      - id: go-generate
        name: Go generate
        language: system
        entry: go generate
        pass_filenames: false
        types: [go, gotmpl]
